package model;
// Generated Dec 5, 2020, 1:49:07 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Albums generated by hbm2java
 */
@Entity
@Table(name = "ALBUMS", schema = "dbo", catalog = "Website_UploadImages")
public class Albums implements java.io.Serializable {

	private Integer albumId;
	private Tags tags;
	private Users users;
	private String albumName;
	private String albumCaption;
	private Set<Shared> shareds = new HashSet<Shared>(0);
	private Set<Images> imageses = new HashSet<Images>(0);

	public Albums() {
	}

	public Albums(Tags tags, Users users, String albumName, String albumCaption, Set<Shared> shareds,
			Set<Images> imageses) {
		this.tags = tags;
		this.users = users;
		this.albumName = albumName;
		this.albumCaption = albumCaption;
		this.shareds = shareds;
		this.imageses = imageses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "AlbumID", unique = true, nullable = false)
	public Integer getAlbumId() {
		return this.albumId;
	}

	public void setAlbumId(Integer albumId) {
		this.albumId = albumId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "Tagid")
	public Tags getTags() {
		return this.tags;
	}

	public void setTags(Tags tags) {
		this.tags = tags;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UserID")
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "AlbumName")
	public String getAlbumName() {
		return this.albumName;
	}

	public void setAlbumName(String albumName) {
		this.albumName = albumName;
	}

	@Column(name = "AlbumCaption")
	public String getAlbumCaption() {
		return this.albumCaption;
	}

	public void setAlbumCaption(String albumCaption) {
		this.albumCaption = albumCaption;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "albums")
	public Set<Shared> getShareds() {
		return this.shareds;
	}

	public void setShareds(Set<Shared> shareds) {
		this.shareds = shareds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "albums")
	public Set<Images> getImageses() {
		return this.imageses;
	}

	public void setImageses(Set<Images> imageses) {
		this.imageses = imageses;
	}

}
