package model;
// Generated Dec 5, 2020, 1:49:07 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tags generated by hbm2java
 */
@Entity
@Table(name = "Tags", schema = "dbo", catalog = "Website_UploadImages")
public class Tags implements java.io.Serializable {

	private int tagId;
	private String tagContent;
	private Set<Images> imageses = new HashSet<Images>(0);
	private Set<Albums> albumses = new HashSet<Albums>(0);

	public Tags() {
	}

	public Tags(int tagId) {
		this.tagId = tagId;
	}

	public Tags(int tagId, String tagContent, Set<Images> imageses, Set<Albums> albumses) {
		this.tagId = tagId;
		this.tagContent = tagContent;
		this.imageses = imageses;
		this.albumses = albumses;
	}

	@Id

	@Column(name = "TagID", unique = true, nullable = false)
	public int getTagId() {
		return this.tagId;
	}

	public void setTagId(int tagId) {
		this.tagId = tagId;
	}

	@Column(name = "TagContent")
	public String getTagContent() {
		return this.tagContent;
	}

	public void setTagContent(String tagContent) {
		this.tagContent = tagContent;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tags")
	public Set<Images> getImageses() {
		return this.imageses;
	}

	public void setImageses(Set<Images> imageses) {
		this.imageses = imageses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tags")
	public Set<Albums> getAlbumses() {
		return this.albumses;
	}

	public void setAlbumses(Set<Albums> albumses) {
		this.albumses = albumses;
	}

}
