package model;
// Generated Dec 5, 2020, 1:49:07 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "USERS", schema = "dbo", catalog = "Website_UploadImages")
public class Users implements java.io.Serializable {

	private Integer userId;
	private String userName;
	private Date userNgaySinh;
	private String userPhone;
	private String userEmail;
	private String userAddress;
	private String passwords;
	private Set<Images> imageses = new HashSet<Images>(0);
	private Set<Shared> shareds = new HashSet<Shared>(0);
	private Set<Albums> albumses = new HashSet<Albums>(0);

	public Users() {
	}

	public Users(String userName, Date userNgaySinh, String userPhone, String userEmail, String userAddress,
			String passwords, Set<Images> imageses, Set<Shared> shareds, Set<Albums> albumses) {
		this.userName = userName;
		this.userNgaySinh = userNgaySinh;
		this.userPhone = userPhone;
		this.userEmail = userEmail;
		this.userAddress = userAddress;
		this.passwords = passwords;
		this.imageses = imageses;
		this.shareds = shareds;
		this.albumses = albumses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "UserID", unique = true, nullable = false)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "UserName")
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "UserNgaySinh", length = 10)
	public Date getUserNgaySinh() {
		return this.userNgaySinh;
	}

	public void setUserNgaySinh(Date userNgaySinh) {
		this.userNgaySinh = userNgaySinh;
	}

	@Column(name = "UserPhone", length = 10)
	public String getUserPhone() {
		return this.userPhone;
	}

	public void setUserPhone(String userPhone) {
		this.userPhone = userPhone;
	}

	@Column(name = "UserEmail", length = 50)
	public String getUserEmail() {
		return this.userEmail;
	}

	public void setUserEmail(String userEmail) {
		this.userEmail = userEmail;
	}

	@Column(name = "UserAddress")
	public String getUserAddress() {
		return this.userAddress;
	}

	public void setUserAddress(String userAddress) {
		this.userAddress = userAddress;
	}

	@Column(name = "Passwords", length = 50)
	public String getPasswords() {
		return this.passwords;
	}

	public void setPasswords(String passwords) {
		this.passwords = passwords;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Images> getImageses() {
		return this.imageses;
	}

	public void setImageses(Set<Images> imageses) {
		this.imageses = imageses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Shared> getShareds() {
		return this.shareds;
	}

	public void setShareds(Set<Shared> shareds) {
		this.shareds = shareds;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "users")
	public Set<Albums> getAlbumses() {
		return this.albumses;
	}

	public void setAlbumses(Set<Albums> albumses) {
		this.albumses = albumses;
	}

}
